#!/bin/bash

USERID=$(id -u)

if [ $USERID -eq 0 ]   #id -u (when root asscess, it will return 0)
then
    echo "You are running with root access"
    exit 1 #give other than 0 upto 127
else
    echo "ERROR:: Please run this script with root access"
fi
